server:
  port: 4396
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://121.4.69.199:3306/mc_soul?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis的配置
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:com/mc/mcsoul/dao/mapper/*Mapper.xml
  type-aliases-package: com.mc.mcsoul.entity
